[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "UnderWaterWorkspaceDemo"
version = "1.0.0"

dependencies = [
    "opencv-python==4.10.0.84",
    "pymavlink==2.4.35",  
    "pyserial==3.5"       
]

[project.scripts]

